In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [4]:
b.dtype

dtype('int32')

In [5]:
b.ndim

2

In [6]:
print(type(b))

<class 'numpy.ndarray'>


In [7]:
c = np.arange(100)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
data = range(10000)
%timeit [i ** 3 for i in data]

data = np.arange(10000)
%timeit (data ** 3)

520 µs ± 7.58 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
13.9 µs ± 305 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
l1 = list(range(10000))
l2 = [i**2 for i in l1]

In [10]:
%timeit list(map(lambda x,y: x*y, l1, l2))

588 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [11]:
a1 = np.array(l1)
a2 = np.array(l2)

In [12]:
%timeit (a1 * a2)

5.29 µs ± 137 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [13]:
print(np.arange(10))
print(np.arange(2, 10))
print(np.arange(2, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]


In [14]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.eye(3)  # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.full((3, 3), 2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [18]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [19]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

In [20]:
np.tile(v, (3, 1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [21]:
np.tile(v, (3, 2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [22]:
np.random.random()

0.48386409946670716

In [23]:
2 + np.random.random() * 50

29.69680470394408

In [24]:
np.random.random([3, 3])

array([[0.65898462, 0.82990423, 0.77897878],
       [0.90778388, 0.0671031 , 0.61906458],
       [0.20629163, 0.21151701, 0.04620025]])

In [25]:
a = np.linspace(0, 50, 100)
a

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

In [26]:
a.itemsize

8

In [27]:
a = np.arange(18)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [28]:
b = a.reshape((2, 3, 3))
# or if other dimension length is unknown or not yet calculated
b = a.reshape((2, 3, -1))
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [29]:
b.shape

(2, 3, 3)

In [30]:
a = np.arange(2, 20, 2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
a[0]

2

In [32]:
a[2]

6

In [33]:
a[[2, 4, 6]]

array([ 6, 10, 14])

In [34]:
a[2:]

array([ 6,  8, 10, 12, 14, 16, 18])

In [35]:
a[2:5]

array([ 6,  8, 10])

In [36]:
a[0::2]

array([ 2,  6, 10, 14, 18])

In [37]:
a = np.random.random([3, 3])
a

array([[0.84257777, 0.08523205, 0.22249032],
       [0.37802736, 0.18613191, 0.93573627],
       [0.64942892, 0.54720466, 0.65656068]])

In [38]:
a[2, 2]

0.6565606822684661

In [39]:
a > 0.5

array([[ True, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [40]:
a[(a > 0.05) & (a < 0.5)]

array([0.08523205, 0.22249032, 0.37802736, 0.18613191])

In [41]:
b = a.copy()

In [42]:
b  # changing b will not affect a

array([[0.84257777, 0.08523205, 0.22249032],
       [0.37802736, 0.18613191, 0.93573627],
       [0.64942892, 0.54720466, 0.65656068]])

In [43]:
np.shares_memory(a, b)

False

In [44]:
c = a
np.shares_memory(a, c)

True

In [45]:
a

array([[0.84257777, 0.08523205, 0.22249032],
       [0.37802736, 0.18613191, 0.93573627],
       [0.64942892, 0.54720466, 0.65656068]])

In [46]:
a.T  # transpose

array([[0.84257777, 0.37802736, 0.64942892],
       [0.08523205, 0.18613191, 0.54720466],
       [0.22249032, 0.93573627, 0.65656068]])

In [47]:
a2 = np.random.random([3, 3])
a2

array([[0.47458886, 0.02198519, 0.980863  ],
       [0.23708298, 0.44890419, 0.83118705],
       [0.38031902, 0.54924363, 0.78784199]])

In [48]:
a == a2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [49]:
np.vstack((a, b))

array([[0.84257777, 0.08523205, 0.22249032],
       [0.37802736, 0.18613191, 0.93573627],
       [0.64942892, 0.54720466, 0.65656068],
       [0.84257777, 0.08523205, 0.22249032],
       [0.37802736, 0.18613191, 0.93573627],
       [0.64942892, 0.54720466, 0.65656068]])

In [50]:
np.hstack((a, b))

array([[0.84257777, 0.08523205, 0.22249032, 0.84257777, 0.08523205,
        0.22249032],
       [0.37802736, 0.18613191, 0.93573627, 0.37802736, 0.18613191,
        0.93573627],
       [0.64942892, 0.54720466, 0.65656068, 0.64942892, 0.54720466,
        0.65656068]])

In [51]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [53]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [54]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [55]:
np.sum(a)

45

In [56]:
np.median(a)

4.5

In [57]:
np.std(a), a.std()

(2.8722813232690143, 2.8722813232690143)

In [58]:
a = np.random.random([3, 3]) * 10
a

array([[9.25527885, 6.1745974 , 6.80132769],
       [4.65722871, 7.76492043, 8.71787427],
       [1.74581303, 9.31879833, 7.67065788]])

In [59]:
np.linalg.det(a)

-124.26527173291485

In [60]:
np.linalg.inv(a)

array([[ 0.1744499 , -0.12889343, -0.0081889 ],
       [ 0.1650037 , -0.47575827,  0.3944064 ],
       [-0.24016103,  0.60731678, -0.34691906]])

In [61]:
np.linalg.eig(a)

EigResult(eigenvalues=array([20.45608292,  5.36670438, -1.13193014]), eigenvectors=array([[-0.63167592, -0.88674909, -0.07682097],
       [-0.58289117,  0.05258254, -0.67701291],
       [-0.5111002 ,  0.45925061,  0.73195086]]))

In [62]:
np.dot(a, b)

array([[14.54943782,  5.65985421, 12.30248901],
       [12.52106938,  6.61270606, 14.02591945],
       [ 9.97529101,  6.08074472, 14.14461647]])

In [63]:
b1 = np.array([1, 1, 0], dtype=bool)
b2 = np.array([1, 0, 1], dtype=bool)

np.logical_or(b1, b2)

array([ True,  True,  True])

In [64]:
np.logical_and(b1, b2)

array([ True, False, False])

In [65]:
b1 == b1

array([ True,  True,  True])

In [66]:
np.all(b1 == b1)

True

In [67]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [68]:
a.sum()

10

In [69]:
a.sum(axis=0)

array([4, 6])

In [70]:
a.sum(axis=1)

array([3, 7])

In [71]:
a.max()

4

In [72]:
a.argmax()

3

In [73]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a.shape

(9,)

In [75]:
a[:, np.newaxis].shape

(9, 1)

In [76]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [77]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])