In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
a = np.array([3, 4, 5])
b = np.array([1, 3, 6])

In [3]:
np.dot(a, b)

45

In [4]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [2, 3, 4, 5], [6, 7, 8, 9]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [6, 7, 8, 9]])

In [5]:
x.shape

(4, 4)

In [6]:
a = np.array([[1, 4, 5], [2, 4, 3], [5, 6, 8]])
a

array([[1, 4, 5],
       [2, 4, 3],
       [5, 6, 8]])

In [7]:
b = np.matrix([[2], [4], [5]])
b

matrix([[2],
        [4],
        [5]])

In [8]:
a * b  # cross product

matrix([[43],
        [35],
        [74]])

In [9]:
x = np.matrix([[1, 3, 1], [2, 2, 1], [3, 5, 3]])
x

matrix([[1, 3, 1],
        [2, 2, 1],
        [3, 5, 3]])

In [10]:
x.shape

(3, 3)

In [11]:
LA.matrix_rank(x)

3